import type {
  AnalyticsResponse,
  BrandAttachmentListResponse,
  BrandAttachmentResponse,
  BrandOverviewResponse,
  BrandResponse,
  ChatMessageResponse,
  ChatSendResponse,
  ChatSessionResponse,
  ContentVersionResponse,
  CurrentUserResponse,
  KnowledgeAssetResponse,
  LoginResponse,
  RenderResponse,
  ReviewDetailResponse,
  ReviewLinkResponse,
  ResolvedBrandContextResponse,
  TenantLogoUploadRequest,
  TenantBrandSpaceSummaryResponse,
  TenantCreateResponse,
  TenantSummaryResponse,
  TenantUsageSummary,
  TenantUserResponse,
  TemplateResponse,
  TemplateRecommendationResponse,
  TokenPairResponse,
  ToneEvaluationResponse,
  TwoFactorSetupResponse,
  ValidationSummaryResponse,
} from "@/lib/api/contracts";

export type HttpMethod = "GET" | "POST" | "PUT" | "DELETE" | "PATCH";

export interface ApiEndpoint<TReq = unknown, TRes = unknown> {
  method: HttpMethod;
  url: string | ((params: unknown) => string);
  __requestType?: TReq;
  __responseType?: TRes;
}

export const API = {
  AUTH: {
    LOGIN: { method: "POST", url: "/api/v1/auth/login" } as ApiEndpoint<{ email: string; password: string }, LoginResponse>,
    REFRESH: { method: "POST", url: "/api/v1/auth/refresh" } as ApiEndpoint<{ refresh_token: string }, TokenPairResponse>,
    ACTIVATE: { method: "POST", url: "/api/v1/auth/activate" } as ApiEndpoint<{ token: string; password: string }, TokenPairResponse>,
    FORGOT_PASSWORD: { method: "POST", url: "/api/v1/auth/forgot-password" } as ApiEndpoint<{ email: string }, { message: string; reset_token?: string }>,
    RESET_PASSWORD: { method: "POST", url: "/api/v1/auth/reset-password" } as ApiEndpoint<{ token: string; password: string }, TokenPairResponse>,
    PROFILE: { method: "GET", url: "/api/v1/auth/profile" } as ApiEndpoint<void, CurrentUserResponse>,
    UPDATE_PROFILE: { method: "PUT", url: "/api/v1/auth/profile" } as ApiEndpoint<{ full_name?: string; email?: string; phone_number?: string; notifications_enabled?: boolean }, CurrentUserResponse>,
    CHANGE_PASSWORD: { method: "POST", url: "/api/v1/auth/change-password" } as ApiEndpoint<{ current_password: string; new_password: string }, { message: string }>,
    DELETE_PROFILE: { method: "DELETE", url: "/api/v1/auth/profile" } as ApiEndpoint<void, { message: string }>,
    TWO_FACTOR_STATUS: { method: "GET", url: "/api/v1/auth/2fa/status" } as ApiEndpoint<void, TwoFactorSetupResponse>,
    TWO_FACTOR_SETUP: { method: "POST", url: "/api/v1/auth/2fa/setup" } as ApiEndpoint<void, TwoFactorSetupResponse>,
    TWO_FACTOR_ENABLE: { method: "POST", url: "/api/v1/auth/2fa/enable" } as ApiEndpoint<{ code: string }, TwoFactorSetupResponse>,
    TWO_FACTOR_DISABLE: { method: "POST", url: "/api/v1/auth/2fa/disable" } as ApiEndpoint<{ code: string }, TwoFactorSetupResponse>,
    TWO_FACTOR_VERIFY: { method: "POST", url: "/api/v1/auth/2fa/verify" } as ApiEndpoint<{ ticket: string; code: string }, TokenPairResponse>,
  },
  USER: {
    GET_ME: { method: "GET", url: "/api/v1/auth/me" } as ApiEndpoint<void, CurrentUserResponse>,
  },
  TENANTS: {
    LIST: { method: "GET", url: "/api/v1/tenants" } as ApiEndpoint<void, TenantSummaryResponse[]>,
    CREATE: { method: "POST", url: "/api/v1/tenants" } as ApiEndpoint<unknown, TenantCreateResponse>,
    DETAIL: { method: "GET", url: (tenantId: string) => `/api/v1/tenants/${tenantId}` } as ApiEndpoint<void, TenantSummaryResponse>,
    UPDATE: { method: "PUT", url: (tenantId: string) => `/api/v1/tenants/${tenantId}` } as ApiEndpoint<unknown, TenantSummaryResponse>,
    UPLOAD_LOGO: { method: "POST", url: (tenantId: string) => `/api/v1/tenants/${tenantId}/logo` } as ApiEndpoint<TenantLogoUploadRequest, TenantSummaryResponse>,
    USERS: { method: "GET", url: (tenantId: string) => `/api/v1/tenants/${tenantId}/users` } as ApiEndpoint<void, TenantUserResponse[]>,
    BRAND_SPACES: { method: "GET", url: (tenantId: string) => `/api/v1/tenants/${tenantId}/brand-spaces` } as ApiEndpoint<void, TenantBrandSpaceSummaryResponse[]>,
    CREATE_USER: { method: "POST", url: (tenantId: string) => `/api/v1/tenants/${tenantId}/users` } as ApiEndpoint<unknown, TenantUserResponse>,
    USER_DETAIL: { method: "GET", url: ({ tenantId, userId }: { tenantId: string; userId: string }) => `/api/v1/tenants/${tenantId}/users/${userId}` } as ApiEndpoint<void, TenantUserResponse>,
    UPDATE_USER: { method: "PUT", url: ({ tenantId, userId }: { tenantId: string; userId: string }) => `/api/v1/tenants/${tenantId}/users/${userId}` } as ApiEndpoint<unknown, TenantUserResponse>,
    DEACTIVATE_USER: { method: "POST", url: ({ tenantId, userId }: { tenantId: string; userId: string }) => `/api/v1/tenants/${tenantId}/users/${userId}/deactivate` } as ApiEndpoint<void, { message: string }>,
    UPDATE_USAGE: { method: "PUT", url: (tenantId: string) => `/api/v1/tenants/${tenantId}/usage-limits` } as ApiEndpoint<unknown, { message: string }>,
    USAGE_SUMMARY: { method: "GET", url: (tenantId: string) => `/api/v1/tenants/${tenantId}/usage-summary` } as ApiEndpoint<void, TenantUsageSummary>,
  },
  BRANDS: {
    LIST: { method: "GET", url: "/api/v1/brands" } as ApiEndpoint<void, BrandResponse[]>,
    CREATE: { method: "POST", url: "/api/v1/brands" } as ApiEndpoint<unknown, BrandResponse>,
    DETAIL: { method: "GET", url: (brandId: string) => `/api/v1/brands/${brandId}` } as ApiEndpoint<void, BrandResponse>,
    UPDATE: { method: "PUT", url: (brandId: string) => `/api/v1/brands/${brandId}` } as ApiEndpoint<unknown, BrandResponse>,
    UPSERT_SECTION: { method: "PUT", url: ({ brandId, sectionCode }: { brandId: string; sectionCode: string }) => `/api/v1/brands/${brandId}/sections/${sectionCode}` } as ApiEndpoint<unknown, BrandResponse>,
    FINALIZE: { method: "POST", url: (brandId: string) => `/api/v1/brands/${brandId}/finalize` } as ApiEndpoint<{ review_notes?: string }, BrandResponse>,
    PUBLISH: { method: "POST", url: (brandId: string) => `/api/v1/brands/${brandId}/publish` } as ApiEndpoint<void, BrandResponse>,
    UNPUBLISH: { method: "POST", url: (brandId: string) => `/api/v1/brands/${brandId}/unpublish` } as ApiEndpoint<void, BrandResponse>,
    ARCHIVE: { method: "POST", url: (brandId: string) => `/api/v1/brands/${brandId}/archive` } as ApiEndpoint<void, BrandResponse>,
    RESTORE: { method: "POST", url: (brandId: string) => `/api/v1/brands/${brandId}/restore` } as ApiEndpoint<void, BrandResponse>,
    DELETE: { method: "DELETE", url: (brandId: string) => `/api/v1/brands/${brandId}` } as ApiEndpoint<void, { message: string }>,
    OVERVIEW: { method: "GET", url: (brandId: string) => `/api/v1/brands/${brandId}/overview` } as ApiEndpoint<void, BrandOverviewResponse>,
    VALIDATION: { method: "GET", url: (brandId: string) => `/api/v1/brands/${brandId}/validation` } as ApiEndpoint<void, ValidationSummaryResponse>,
    RESOLVED_CONTEXT: { method: "GET", url: (brandId: string) => `/api/v1/brands/${brandId}/resolved-context` } as ApiEndpoint<void, ResolvedBrandContextResponse>,
    ATTACHMENTS: { method: "GET", url: (brandId: string) => `/api/v1/brands/${brandId}/attachments` } as ApiEndpoint<void, BrandAttachmentListResponse[]>,
    ATTACHMENTS_BY_FIELD: { method: "GET", url: ({ brandId, fieldKey }: { brandId: string; fieldKey: string }) => `/api/v1/brands/${brandId}/attachments/fields/${fieldKey}` } as ApiEndpoint<void, BrandAttachmentListResponse>,
    UPLOAD_ATTACHMENT: { method: "POST", url: ({ brandId, fieldKey }: { brandId: string; fieldKey: string }) => `/api/v1/brands/${brandId}/attachments/${fieldKey}` } as ApiEndpoint<unknown, BrandAttachmentResponse>,
    ATTACHMENT_DETAIL: { method: "GET", url: ({ brandId, assetId }: { brandId: string; assetId: string }) => `/api/v1/brands/${brandId}/attachments/assets/${assetId}` } as ApiEndpoint<void, BrandAttachmentResponse>,
    ATTACHMENT_REPROCESS: { method: "POST", url: ({ brandId, assetId }: { brandId: string; assetId: string }) => `/api/v1/brands/${brandId}/attachments/assets/${assetId}/reprocess` } as ApiEndpoint<void, { asset: BrandAttachmentResponse; message: string }>,
    ATTACHMENT_UNSYNC: { method: "POST", url: ({ brandId, assetId }: { brandId: string; assetId: string }) => `/api/v1/brands/${brandId}/attachments/assets/${assetId}/unsync` } as ApiEndpoint<void, { asset: BrandAttachmentResponse; message: string }>,
    ATTACHMENT_DELETE: { method: "DELETE", url: ({ brandId, assetId }: { brandId: string; assetId: string }) => `/api/v1/brands/${brandId}/attachments/assets/${assetId}` } as ApiEndpoint<void, { asset: BrandAttachmentResponse; message: string }>,
  },
  KNOWLEDGE: {
    UPLOAD: { method: "POST", url: "/api/v1/knowledge/upload" } as ApiEndpoint<unknown, KnowledgeAssetResponse>,
    LIST: { method: "GET", url: "/api/v1/knowledge/list" } as ApiEndpoint<void, KnowledgeAssetResponse[]>,
    STATUS: { method: "GET", url: (knowledgeId: string) => `/api/v1/knowledge/${knowledgeId}/status` } as ApiEndpoint<void, KnowledgeAssetResponse>,
  },
  TEMPLATES: {
    UPLOAD: { method: "POST", url: "/api/v1/templates/upload" } as ApiEndpoint<unknown, TemplateResponse>,
    LIST: { method: "GET", url: "/api/v1/templates/list" } as ApiEndpoint<void, TemplateResponse[]>,
    DETAIL: { method: "GET", url: (templateId: string) => `/api/v1/templates/${templateId}` } as ApiEndpoint<void, { template: TemplateResponse; metadata: Record<string, unknown> }>,
    RECOMMEND: { method: "POST", url: "/api/v1/templates/recommend" } as ApiEndpoint<unknown, TemplateRecommendationResponse[]>,
  },
  CONTENT: {
    GENERATE: { method: "POST", url: "/api/v1/content/generate" } as ApiEndpoint<unknown, ContentVersionResponse>,
    REWRITE: { method: "POST", url: "/api/v1/content/rewrite" } as ApiEndpoint<unknown, ContentVersionResponse>,
    TONE_CHECK: { method: "POST", url: "/api/v1/content/tone-check" } as ApiEndpoint<unknown, ToneEvaluationResponse>,
    HISTORY: { method: "GET", url: "/api/v1/content/history" } as ApiEndpoint<void, ContentVersionResponse[]>,
    DETAIL: { method: "GET", url: (contentId: string) => `/api/v1/content/${contentId}` } as ApiEndpoint<void, ContentVersionResponse>,
    EXPORT: { method: "POST", url: "/api/v1/content/export" } as ApiEndpoint<unknown, RenderResponse>,
  },
  CHAT: {
    CREATE_SESSION: { method: "POST", url: "/api/v1/chat/sessions" } as ApiEndpoint<unknown, ChatSessionResponse>,
    LIST_SESSIONS: { method: "GET", url: "/api/v1/chat/sessions" } as ApiEndpoint<void, ChatSessionResponse[]>,
    LIST_MESSAGES: { method: "GET", url: (sessionId: string) => `/api/v1/chat/sessions/${sessionId}/messages` } as ApiEndpoint<void, ChatMessageResponse[]>,
    SEND_MESSAGE: { method: "POST", url: (sessionId: string) => `/api/v1/chat/sessions/${sessionId}/messages` } as ApiEndpoint<unknown, ChatSendResponse>,
  },
  REVIEW: {
    CREATE_LINK: { method: "POST", url: "/api/v1/review/share-link" } as ApiEndpoint<unknown, ReviewLinkResponse>,
    DETAIL: { method: "GET", url: (token: string) => `/api/v1/review/${token}` } as ApiEndpoint<void, ReviewDetailResponse>,
    ADD_COMMENT: { method: "POST", url: (token: string) => `/api/v1/review/${token}/comment` } as ApiEndpoint<unknown, ReviewDetailResponse["comments"][number]>,
    UPDATE_STATUS: { method: "POST", url: (token: string) => `/api/v1/review/${token}/status` } as ApiEndpoint<{ status: string }, ReviewLinkResponse>,
  },
  ANALYTICS: {
    PLATFORM: { method: "GET", url: "/api/v1/analytics/platform" } as ApiEndpoint<void, AnalyticsResponse>,
    TENANT: { method: "GET", url: "/api/v1/analytics/tenant" } as ApiEndpoint<void, AnalyticsResponse>,
    BRAND: { method: "GET", url: (brandId: string) => `/api/v1/analytics/brand/${brandId}` } as ApiEndpoint<void, AnalyticsResponse>,
    USAGE_SUMMARY: { method: "GET", url: "/api/v1/analytics/usage-summary" } as ApiEndpoint<void, AnalyticsResponse>,
  },
} as const;
